version: "3"
services:
    gym:
        extends:
            file: base-compose.yml
            service: python3-gym-dev
        environment:
            - FWD_MODEL_CONNECTION_STRING=ws://fwd-server:6969/?role=admin
        depends_on:
            - fwd-server
        networks:
            - coderone-open-ai-gym-wrapper

    fwd-server:
        extends:
            file: base-compose.yml
            service: game-server
        environment:
            - ADMIN_ROLE_ENABLED=1
            - TELEMETRY_ENABLED=0
            - PORT=6969
            - WORLD_SEED=1234
            - PRNG_SEED=1234
            - UNITS_PER_AGENT=3
            - TRAINING_MODE_ENABLED=0
        networks:
            - coderone-open-ai-gym-wrapper
networks:
    coderone-open-ai-gym-wrapper: null
