FROM python:3.8-bullseye

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN python -m pip install -r requirements.txt
ENV PYTHONUNBUFFERED=1
ENTRYPOINT ["python3", "dev_gym.py"]
